const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { Store } = require('../src/store');
const conversation = require('../src/career-conversation');
const understanding = require('../src/career-understanding');
const { execFileSync } = require('node:child_process');

function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'career-understanding-')); const store = new Store(path.join(dir, 'test.db')); try { run(store); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function profile(store) { return store.createProfile({ name: 'Synthetic Candidate' }); }
function conversationRun(store, candidate, answer) { const job = store.createJobRequirementProfile({ company: 'Acme', roleTitle: 'Analyst', jobDescription: 'Required Qualifications:\nSQL required.' }); const needs = store.createInformationNeedRun({ candidateProfileId: candidate.id, jobRequirementProfileId: job.id }); const discovery = store.createEvidenceDiscoveryRun({ informationNeedRunId: needs.id }); const review = store.createEvidenceReviewRun({ candidateProfileId: candidate.id, jobRequirementProfileId: job.id, evidenceDiscoveryRunId: discovery.id, decisions: [] }); return conversation.observe({ store, reviewRun: review, answer }); }
function committedFact(store, candidate, entityType, value) { const now = store.now(); const integrationRun = store.id(); const decision = store.id(); const id = store.id(); store.db.prepare('INSERT INTO candidate_knowledge_integration_runs VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(integrationRun, candidate.id, 'evidence_discovery_run', `synthetic-${id}`, 'synthetic/1', '[]', '{}', 'Synthetic committed-fixture provenance.', now); store.db.prepare('INSERT INTO integration_decisions VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(decision, integrationRun, entityType, JSON.stringify({ name: value }), '[]', '[]', '{}', 'accepted', 'Synthetic accepted fact.', 'confirmed', 'high', 'synthetic/1', null, now); store.db.prepare('INSERT INTO candidate_knowledge_facts VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, candidate.id, entityType, JSON.stringify({ name: value }), value, `${entityType}:${value}`, 'confirmed', 'high', null, decision, now); }
test('user-confirmed direction is explainable and unknowns remain visible', () => withStore((store) => { const candidate = profile(store); conversationRun(store, candidate, 'Data Analytics'); const run = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); const direction = run.understanding_items.find((entry) => entry.category === 'direction'); assert.deepEqual({ label: direction.label, state: direction.state, confidence: direction.confidence }, { label: 'Data Analytics', state: 'user_confirmed', confidence: 'medium' }); assert.ok(direction.supporting_source_references.length); assert.match(direction.rationale, /selected Data Analytics/); assert.ok(run.unknowns.includes('Preferred industry')); }));
test('committed Python and Power BI are explicit strengths with provenance', () => withStore((store) => { const candidate = profile(store); for (const value of ['Python', 'Power BI']) committedFact(store, candidate, 'skill', value); const run = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); assert.deepEqual(run.understanding_items.map((entry) => entry.label).sort(), ['Power BI', 'Python']); assert.ok(run.understanding_items.every((entry) => entry.state === 'explicit' && entry.supporting_source_references.length && entry.rationale)); }));
test('unsupported Candidate Knowledge entities never appear as strengths or working style', () => withStore((store) => { const candidate = profile(store); for (const [entityType, value] of [['employment', 'Analyst at Acme'], ['education', 'BSc Statistics'], ['certification', 'PMP'], ['project', 'Forecasting'], ['achievement', 'Improved retention'], ['working_style', 'Collaborative']]) committedFact(store, candidate, entityType, value); const run = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); assert.deepEqual(run.understanding_items, []); assert.ok(run.unknowns.includes('Preferred work style')); }));
test('applications are neutral and cannot create industry preference; repeated signals remain bounded', () => withStore((store) => { const candidate = profile(store); store.createApplication({ profileId: candidate.id, company: 'North', roleTitle: 'Insurance Analyst', jobDescription: 'Synthetic', applicationDate: '2026-08-01' }); store.createApplication({ profileId: candidate.id, company: 'South', roleTitle: 'Insurance Analyst', jobDescription: 'Synthetic', applicationDate: '2026-08-02' }); const run = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); assert.equal(run.understanding_items.some((entry) => /industry|insurance/i.test(entry.label)), false); assert.equal(run.neutral_activity_signals.length, 2); }));
test('snapshot runs and feedback are immutable and feedback does not change knowledge', () => withStore((store) => { const candidate = profile(store); const one = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); const two = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); assert.notEqual(one.id, two.id); const before = store.getCommittedCandidateKnowledge(candidate.id); store.recordCareerUnderstandingFeedback({ snapshotRunId: one.id, action: 'looks_right' }); store.recordCareerUnderstandingFeedback({ snapshotRunId: one.id, action: 'not_quite', note: 'Needs more context' }); assert.equal(store.getCareerUnderstandingSnapshotRun(one.id).feedback_state, 'not_quite'); assert.deepEqual(store.getCommittedCandidateKnowledge(candidate.id), before); assert.match(understanding.readable(one), /Current Career Snapshot/); }));
test('career-snapshot CLI prints readable text and JSON output', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'career-snapshot-cli-')); const db = path.join(dir, 'test.db'); const store = new Store(db); const candidate = profile(store); conversationRun(store, candidate, 'Data Analytics'); store.close(); try { const root = path.resolve(__dirname, '..'); const text = execFileSync(process.execPath, ['src/cli.js', 'career-snapshot-show', '--db', db, '--candidate-profile-id', candidate.id, '--format', 'text'], { cwd: root, encoding: 'utf8' }); const json = execFileSync(process.execPath, ['src/cli.js', 'career-snapshot-show', '--db', db, '--candidate-profile-id', candidate.id], { cwd: root, encoding: 'utf8' }); assert.match(text, /Current Career Snapshot/); assert.match(text, /Data Analytics.*user confirmed.*medium confidence/); assert.equal(JSON.parse(json).current_direction.label, 'Data Analytics'); } finally { fs.rmSync(dir, { recursive: true, force: true }); } });
