const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { Store } = require('../src/store');
const reflection = require('../src/career-reflection');
const { runDemo } = require('../src/demo');

function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'career-reflection-')); const store = new Store(path.join(dir, 'test.db')); try { run(store, dir); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function snapshot(store) { const candidate = store.createProfile({ name: 'Synthetic Candidate' }); return { candidate, snapshot: store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }) }; }

for (const [action, note] of [['looks_right', null], ['not_quite', 'This misses a recent project.'], ['missing_something', 'Community work matters here.']]) test(`${action} persists an immutable source-linked reflection without a follow-up`, () => withStore((store) => {
  const { candidate, snapshot: snapshotRun } = snapshot(store); const beforeFacts = store.getCommittedCandidateKnowledge(candidate.id); const beforeItems = JSON.stringify(snapshotRun.understanding_items);
  const run = store.recordCareerReflectionRun({ snapshotRunId: snapshotRun.id, action, note });
  assert.equal(run.action, action); assert.equal(run.note, note); assert.equal(run.actor, 'user'); assert.equal(run.career_understanding_snapshot_run_id, snapshotRun.id); assert.equal(run.source_snapshot_reference.id, snapshotRun.id); assert.ok(run.reflected_at); assert.equal(reflection.PROMPT, 'Does this feel accurate right now?'); assert.deepEqual(store.getCommittedCandidateKnowledge(candidate.id), beforeFacts); assert.equal(JSON.stringify(store.getCareerUnderstandingSnapshotRun(snapshotRun.id).understanding_items), beforeItems);
}));
test('duplicate submissions are idempotent and auditable', () => withStore((store) => { const { snapshot: snapshotRun } = snapshot(store); const first = store.recordCareerReflectionRun({ snapshotRunId: snapshotRun.id, action: 'not_quite', note: 'Needs context.' }); const second = store.recordCareerReflectionRun({ snapshotRunId: snapshotRun.id, action: 'not_quite', note: 'Needs context.' }); assert.equal(second.id, first.id); assert.equal(second.duplicate_submission, true); assert.equal(store.db.prepare('SELECT COUNT(*) AS count FROM career_reflection_runs').get().count, 1); }));
test('CLI renders a readable shared-understanding review and JSON response', () => withStore((store, dir) => { const { candidate, snapshot: snapshotRun } = snapshot(store); const root = path.resolve(__dirname, '..'); const text = execFileSync(process.execPath, ['src/cli.js', 'career-reflection-review', '--db', path.join(dir, 'test.db'), '--snapshot-run-id', snapshotRun.id, '--action', 'looks_right', '--format', 'text'], { cwd: root, encoding: 'utf8' }); const json = execFileSync(process.execPath, ['src/cli.js', 'career-reflection-review', '--db', path.join(dir, 'test.db'), '--candidate-profile-id', candidate.id], { cwd: root, encoding: 'utf8' }); assert.match(text, /Based on what I know today/); assert.match(text, /Does this feel accurate right now\?/); assert.match(text, /Response: looks_right/); assert.equal(JSON.parse(json).reflection_run, null); }));
test('demo writes readable Shared Understanding outputs when recorded and when omitted', async () => { const root = path.resolve(__dirname, '..'); const careerReviewFixturePath = path.join(root, 'examples', 'synthetic-career-review.json'); const evidenceReviewFixturePath = path.join(root, 'examples', 'synthetic-evidence-review.json'); const first = fs.mkdtempSync(path.join(os.tmpdir(), 'career-reflection-demo-')); const second = fs.mkdtempSync(path.join(os.tmpdir(), 'career-reflection-demo-')); try { const recorded = await runDemo({ resumePath: path.join(root, 'examples', 'synthetic-resume.txt'), jobInput: path.join(root, 'examples', 'synthetic-job.txt'), evidenceReviewFixturePath, careerReviewFixturePath, outputDirectory: first, reflectionAction: 'missing_something', reflectionNote: 'Please include volunteer work.' }); assert.equal(recorded.reflection.action, 'missing_something'); assert.equal(JSON.parse(fs.readFileSync(path.join(first, 'career-reflection-run.json'), 'utf8')).note, 'Please include volunteer work.'); assert.match(fs.readFileSync(path.join(first, 'report.html'), 'utf8'), /Shared Understanding/); const omitted = await runDemo({ resumePath: path.join(root, 'examples', 'synthetic-resume.txt'), jobInput: path.join(root, 'examples', 'synthetic-job.txt'), evidenceReviewFixturePath, careerReviewFixturePath, outputDirectory: second }); assert.equal(omitted.reflection, null); assert.equal(JSON.parse(fs.readFileSync(path.join(second, 'career-reflection-run.json'), 'utf8')), null); } finally { fs.rmSync(first, { recursive: true, force: true }); fs.rmSync(second, { recursive: true, force: true }); } });
