const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const { execFileSync } = require('node:child_process');
const { Store } = require('../src/store'); const decisionCompanion = require('../src/decision-companion');
function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'decision-companion-')); const store = new Store(path.join(dir, 'test.db')); try { run(store, dir); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function setup(store) { const candidate = store.createProfile({ name: 'Synthetic' }); const snapshot = store.createCareerUnderstandingSnapshotRun({ candidateProfileId: candidate.id }); return { candidate, snapshot }; }
function decision(options = [{ id: 'a', label: 'Offer A', details: 'A smaller team with hands-on work.' }, { id: 'b', label: 'Offer B', details: 'A larger organization with a structured role.' }], criteria = [{ type: 'learning' }, { type: 'custom', label: 'Manager relationship' }]) { return { title: 'Which offer should I explore?', decisionType: 'job_offer', context: 'Both are meaningful possibilities.', options, criteria }; }

test('supports two through four options and at most three criteria', () => withStore((store) => { const { candidate, snapshot } = setup(store); for (const count of [2, 3, 4]) { const options = Array.from({ length: count }, (_, index) => ({ id: `o${index}`, label: `Option ${index}` })); const run = store.createDecisionCompanionRun({ candidateProfileId: candidate.id, snapshotRunId: snapshot.id, decision: decision(options, [{ type: 'learning' }, { type: 'impact' }, { type: 'custom', label: 'Community' }]), response: { final_state: 'undecided' } }); assert.equal(run.options.length, count); assert.equal(run.criteria.length, 3); } }));
test('rejects unsupported option and criteria counts', () => { assert.throws(() => decisionCompanion.validate(decision([{ id: 'one', label: 'One' }])), /2 to 4/); assert.throws(() => decisionCompanion.validate(decision(Array.from({ length: 5 }, (_, index) => ({ id: `${index}`, label: `${index}` })))), /2 to 4/); assert.throws(() => decisionCompanion.validate(decision(undefined, [{ type: 'learning' }, { type: 'impact' }, { type: 'location' }, { type: 'stability' }])), /up to 3/); });
test('comparison preserves unknowns and provenance without a winner or ranking', () => withStore((store) => { const { candidate, snapshot } = setup(store); const run = store.createDecisionCompanionRun({ candidateProfileId: candidate.id, snapshotRunId: snapshot.id, decision: decision(), response: { final_state: 'need_more_information', note: 'Need to speak with each manager.' } }); assert.equal(run.comparison_entries.length, 2); assert.ok(run.comparison_entries.every((entry) => entry.unknowns.length && entry.provenance.user_inputs.option_id)); assert.equal(run.provenance.source_career_understanding_snapshot_run.id, snapshot.id); assert.doesNotMatch(JSON.stringify(run), /winner|best option|rank|you should/i); assert.equal(run.reflection_question, decisionCompanion.REFLECTION_QUESTION); }));
for (const response of [{ final_state: 'leaning', leaning_option_id: 'a' }, { final_state: 'undecided' }, { final_state: 'need_more_information' }, { final_state: 'stopped' }]) test(`${response.final_state} persists an immutable, read-only run`, () => withStore((store) => { const { candidate, snapshot } = setup(store); const beforeFacts = store.getCommittedCandidateKnowledge(candidate.id); const beforeSnapshot = JSON.stringify(store.getCareerUnderstandingSnapshotRun(snapshot.id)); const run = store.createDecisionCompanionRun({ candidateProfileId: candidate.id, snapshotRunId: snapshot.id, decision: decision(), response }); assert.equal(run.response.final_state, response.final_state); assert.throws(() => store.db.prepare("UPDATE decision_companion_runs SET completed_at = 'x' WHERE id = ?").run(run.id)); assert.deepEqual(store.getCommittedCandidateKnowledge(candidate.id), beforeFacts); assert.equal(JSON.stringify(store.getCareerUnderstandingSnapshotRun(snapshot.id)), beforeSnapshot); }));
test('CLI JSON and text are readable', () => withStore((store, dir) => { const { candidate, snapshot } = setup(store); const root = path.resolve(__dirname, '..'); const payload = JSON.stringify(decision()); const response = JSON.stringify({ final_state: 'undecided' }); const text = execFileSync(process.execPath, ['src/cli.js', 'decision-companion-create', '--db', path.join(dir, 'test.db'), '--candidate-profile-id', candidate.id, '--snapshot-run-id', snapshot.id, '--decision', payload, '--response', response, '--format', 'text'], { cwd: root, encoding: 'utf8' }); assert.match(text, /Decision Companion/); assert.match(text, /Let's think this through together/); assert.match(text, /Options: 2/); }));
