const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { Store } = require('../src/store');
const { REQUIRED_SECTIONS, createDraft } = require('../src/human-review');
const { html } = require('../src/human-review-cli');

function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'human-review-')); const store = new Store(path.join(dir, 'test.db')); try { run(store); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function preparedArtifact(store) {
  const profile = store.createProfile({ name: 'Human Review Candidate' }); const job = store.createJobRequirementProfile({ company: 'Acme', roleTitle: 'Data Analyst', jobDescription: 'Required Qualifications:\nSQL required.\nPython required.' });
  const needs = store.createInformationNeedRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id }); const discovery = store.createEvidenceDiscoveryRun({ informationNeedRunId: needs.id }); const planRun = store.createAcquisitionPlanRun({ informationNeedRunId: needs.id, evidenceDiscoveryRunId: discovery.id }); const action = planRun.acquisition_plans.flatMap((plan) => plan.acquisition_actions)[0]; const result = store.createAcquisitionResultRun({ acquisitionPlanRunId: planRun.id, captures: [{ actionId: action.id, rawCapturedEvidence: { text: 'confirmed' } }] });
  store.createCandidateKnowledgeIntegrationRun({ candidateProfileId: profile.id, acquisitionResultRunId: result.id, proposals: ['SQL', 'Python'].map((name) => ({ entityType: 'skill', value: { name }, confirmationStatus: 'confirmed', confidenceLevel: 'high', sourceEvidenceRefs: [{ type: 'acquisition_result', id: result.acquisition_results[0].id, positiveConfirmation: true }] })) });
  const tailoring = store.createResumeTailoringPlanRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id }); const artifact = store.createResumeArtifactRun({ resumeTailoringPlanRunId: tailoring.id }); store.createResumeValidationRun({ resumeArtifactRunId: artifact.id }); return { profile, artifact };
}
function approvals(store, artifact) { return createDraft({ artifactRun: store.getResumeArtifactRun(artifact.id) }).map(({ section }) => ({ section, action: 'approve' })); }

test('blocks export before a complete Human Review Run', () => withStore((store) => { const { artifact } = preparedArtifact(store); assert.throws(() => store.exportResumeArtifact({ resumeArtifactRunId: artifact.id }), /Export blocked/); }));
test('requires an explicit decision for every presented section', () => withStore((store) => { const { artifact } = preparedArtifact(store); assert.throws(() => store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions: [] }), /explicit decisions/); }));
test('rejects malformed edited section structures before persisting a review run', () => withStore((store) => { const { artifact } = preparedArtifact(store); for (const finalVersion of [{ foo: 'bar' }, { placeholder: 42 }, { statements: {} }, { statements: [{}] }, { statements: [{ text: 'SQL', provenance: 'not-an-object' }] }]) { const decisions = approvals(store, artifact); const index = decisions.findIndex((item) => item.section === 'Skills'); decisions[index] = { section: 'Skills', action: 'edit', finalVersion }; assert.throws(() => store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions }), /Invalid edited Skills section/); } }));
test('approvals persist in an immutable review run and unlock export', () => withStore((store) => { const { artifact } = preparedArtifact(store); const run = store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions: approvals(store, artifact) }); const persisted = store.getHumanReviewRun(run.id); assert.equal(persisted.review_complete, true); assert.ok(persisted.section_reviews.length > 0); assert.ok(persisted.section_reviews.every((item) => item.action === 'approve' && item.reviewed_at)); assert.match(store.exportResumeArtifact({ resumeArtifactRunId: artifact.id, humanReviewRunId: run.id }).markdown, /## Skills/); assert.throws(() => store.db.prepare('UPDATE human_review_runs SET review_actor = ? WHERE id = ?').run('other', run.id), /immutable/); }));
test('blocks export when the latest deterministic validation run fails completeness', () => withStore((store) => { const { artifact } = preparedArtifact(store); const run = store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions: approvals(store, artifact) }); const structured = store.getResumeArtifactRun(artifact.id).resume_artifacts[0]; structured.content.sections.find((item) => item.section === 'Skills').statements = []; store.db.prepare('UPDATE resume_artifacts SET content = ? WHERE id = ?').run(JSON.stringify(structured.content), structured.id); const validation = store.createResumeValidationRun({ resumeArtifactRunId: artifact.id }); assert.equal(validation.validation_status, 'failed'); assert.throws(() => store.exportResumeArtifact({ resumeArtifactRunId: artifact.id, humanReviewRunId: run.id }), /completed passing Resume Validation Run/); }));
test('manual edits preserve the original AI draft and do not write Candidate Knowledge', () => withStore((store) => { const { profile, artifact } = preparedArtifact(store); const before = store.getCommittedCandidateKnowledge(profile.id); const decisions = approvals(store, artifact); const index = decisions.findIndex((item) => item.section === 'Skills'); decisions[index] = { section: 'Skills', action: 'edit', finalVersion: { placeholder: null, statements: [{ text: 'SQL (reviewed wording)' }] } }; const run = store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions }); const skills = store.getHumanReviewRun(run.id).section_reviews.find((item) => item.section === 'Skills'); assert.equal(skills.action, 'edit'); assert.notDeepEqual(skills.ai_version, skills.final_version); assert.match(JSON.stringify(skills.ai_version), /SQL/); assert.match(store.exportReviewedResume({ humanReviewRunId: run.id }).markdown, /SQL \(reviewed wording\)/); assert.deepEqual(store.getCommittedCandidateKnowledge(profile.id), before); }));
test('Career Review is the user-facing label for the existing Human Review run', () => withStore((store) => { const { artifact } = preparedArtifact(store); const run = store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions: approvals(store, artifact) }); const exported = store.exportResumeArtifact({ resumeArtifactRunId: artifact.id, humanReviewRunId: run.id }); const report = html(run, exported); assert.match(report, /Career Review/); assert.match(report, /Approved Resume Export/); assert.ok(!report.includes('<h1>Human Review')); }));
