const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { Store } = require('../src/store');
const { REQUIRED_SECTIONS } = require('../src/human-review');

function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'human-review-')); const store = new Store(path.join(dir, 'test.db')); try { run(store); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function preparedArtifact(store) {
  const profile = store.createProfile({ name: 'Human Review Candidate' }); const job = store.createJobRequirementProfile({ company: 'Acme', roleTitle: 'Data Analyst', jobDescription: 'Required Qualifications:\nSQL required.\nPython required.' });
  const needs = store.createInformationNeedRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id }); const discovery = store.createEvidenceDiscoveryRun({ informationNeedRunId: needs.id }); const planRun = store.createAcquisitionPlanRun({ informationNeedRunId: needs.id, evidenceDiscoveryRunId: discovery.id }); const action = planRun.acquisition_plans.flatMap((plan) => plan.acquisition_actions)[0]; const result = store.createAcquisitionResultRun({ acquisitionPlanRunId: planRun.id, captures: [{ actionId: action.id, rawCapturedEvidence: { text: 'confirmed' } }] });
  store.createCandidateKnowledgeIntegrationRun({ candidateProfileId: profile.id, acquisitionResultRunId: result.id, proposals: ['SQL', 'Python'].map((name) => ({ entityType: 'skill', value: { name }, confirmationStatus: 'confirmed', confidenceLevel: 'high', sourceEvidenceRefs: [{ type: 'acquisition_result', id: result.acquisition_results[0].id, positiveConfirmation: true }] })) });
  const tailoring = store.createResumeTailoringPlanRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id }); return { profile, artifact: store.createResumeArtifactRun({ resumeTailoringPlanRunId: tailoring.id }) };
}
function approvals() { return REQUIRED_SECTIONS.map((section) => ({ section, action: 'approve' })); }

test('blocks export before a complete Human Review Run', () => withStore((store) => { const { artifact } = preparedArtifact(store); assert.throws(() => store.exportResumeArtifact({ resumeArtifactRunId: artifact.id }), /Export blocked/); }));
test('requires an explicit decision for every required section', () => withStore((store) => { const { artifact } = preparedArtifact(store); assert.throws(() => store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions: approvals().slice(0, -1) }), /explicit decisions/); }));
test('approvals persist in an immutable review run and unlock export', () => withStore((store) => { const { artifact } = preparedArtifact(store); const run = store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions: approvals() }); const persisted = store.getHumanReviewRun(run.id); assert.equal(persisted.review_complete, true); assert.equal(persisted.section_reviews.length, 4); assert.ok(persisted.section_reviews.every((item) => item.action === 'approve' && item.reviewed_at)); assert.match(store.exportResumeArtifact({ resumeArtifactRunId: artifact.id, humanReviewRunId: run.id }).markdown, /## Skills/); assert.throws(() => store.db.prepare('UPDATE human_review_runs SET review_actor = ? WHERE id = ?').run('other', run.id), /immutable/); }));
test('manual edits preserve the original AI draft and do not write Candidate Knowledge', () => withStore((store) => { const { profile, artifact } = preparedArtifact(store); const before = store.getCommittedCandidateKnowledge(profile.id); const decisions = approvals(); const index = decisions.findIndex((item) => item.section === 'Skills'); decisions[index] = { section: 'Skills', action: 'edit', finalVersion: { placeholder: null, statements: [{ text: 'SQL (reviewed wording)' }] } }; const run = store.createHumanReviewRun({ resumeArtifactRunId: artifact.id, decisions }); const skills = store.getHumanReviewRun(run.id).section_reviews.find((item) => item.section === 'Skills'); assert.equal(skills.action, 'edit'); assert.notDeepEqual(skills.ai_version, skills.final_version); assert.match(JSON.stringify(skills.ai_version), /SQL/); assert.match(store.exportReviewedResume({ humanReviewRunId: run.id }).markdown, /SQL \(reviewed wording\)/); assert.deepEqual(store.getCommittedCandidateKnowledge(profile.id), before); }));
