const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { Store } = require('../src/store');

function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'resume-validation-')); const store = new Store(path.join(dir, 'test.db')); try { run(store); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function prepared(store) {
  const profile = store.createProfile({ name: 'Synthetic Candidate' });
  const job = store.createJobRequirementProfile({ company: 'Acme', roleTitle: 'Data Analyst', jobDescription: 'Required Qualifications:\nSQL required.\nPython required.' });
  const needs = store.createInformationNeedRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id });
  const discovery = store.createEvidenceDiscoveryRun({ informationNeedRunId: needs.id }); const acquisition = store.createAcquisitionPlanRun({ informationNeedRunId: needs.id, evidenceDiscoveryRunId: discovery.id });
  const action = acquisition.acquisition_plans.flatMap((item) => item.acquisition_actions)[0]; const result = store.createAcquisitionResultRun({ acquisitionPlanRunId: acquisition.id, captures: [{ actionId: action.id, rawCapturedEvidence: { text: 'Confirmed.' } }] });
  store.createCandidateKnowledgeIntegrationRun({ candidateProfileId: profile.id, acquisitionResultRunId: result.id, proposals: ['SQL', 'Python', 'Communication'].map((name) => ({ entityType: 'skill', value: { name }, confirmationStatus: 'confirmed', confidenceLevel: 'high', sourceEvidenceRefs: [{ type: 'acquisition_result', id: result.acquisition_results[0].id, positiveConfirmation: true }] })) });
  const plan = store.createResumeTailoringPlanRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id }); return { plan, artifactRun: store.createResumeArtifactRun({ resumeTailoringPlanRunId: plan.id }) };
}
function artifact(store, run) { return store.getResumeArtifactRun(run.id).resume_artifacts[0]; }
function content(store, run, change) { const item = artifact(store, run); const value = item.content; change(value); store.db.prepare('UPDATE resume_artifacts SET content = ? WHERE id = ?').run(JSON.stringify(value), item.id); }
function errors(run) { return run.validation_findings.filter((item) => ['error', 'critical'].includes(item.severity)); }

test('valid artifact with complete provenance passes', () => withStore((store) => { const setup = prepared(store); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.equal(run.validation_status, 'passed'); assert.equal(run.validation_findings.length, 0); }));
test('statement without selection reference fails', () => withStore((store) => { const setup = prepared(store); content(store, setup.artifactRun, (value) => { value.sections[1].statements[0].resume_content_selection_ids = []; }); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'statement-selection-reference')); }));
test('missing an included selection is a critical completeness failure', () => withStore((store) => { const setup = prepared(store); const included = setup.plan.resume_content_selections.find((item) => item.selection_state === 'include'); content(store, setup.artifactRun, (value) => { for (const section of value.sections) section.statements = section.statements.filter((statement) => !statement.resume_content_selection_ids.includes(included.id)); }); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'included-selection-rendered')); }));
test('selection referencing missing Candidate Fact fails', () => withStore((store) => { const setup = prepared(store); const selection = setup.plan.resume_content_selections.find((item) => item.selection_state === 'include'); store.db.exec('PRAGMA foreign_keys = OFF;'); store.db.prepare('UPDATE resume_content_selections SET candidate_fact_id = ? WHERE id = ?').run('missing-fact', selection.id); store.db.exec('PRAGMA foreign_keys = ON;'); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'candidate-fact-resolves')); }));
test('unsupported advanced SQL or years wording fails when only basic SQL use is permitted', () => withStore((store) => { const setup = prepared(store); content(store, setup.artifactRun, (value) => { value.sections[1].statements[0].text = 'Advanced SQL with 8 years of experience'; }); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'bounded-wording')); }));
test('quantified impact without accepted achievement fact fails', () => withStore((store) => { const setup = prepared(store); content(store, setup.artifactRun, (value) => { value.sections[1].statements[0].text = 'Improved reporting by 20%'; }); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'bounded-wording')); }));
test('blocked or omitted fact appearing in visible output fails', () => withStore((store) => { const setup = prepared(store); const selection = setup.plan.resume_content_selections.find((item) => item.selection_state === 'include'); store.db.prepare("UPDATE resume_content_selections SET selection_state = 'blocked' WHERE id = ?").run(selection.id); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'visible-selection-state')); }));
test('uncovered requirement appearing as supported claim fails', () => withStore((store) => { const setup = prepared(store); const selection = setup.plan.resume_content_selections.find((item) => item.selection_state === 'include'); const coverage = setup.plan.requirement_coverage[0]; store.db.prepare("UPDATE requirement_coverage SET coverage_status = 'uncovered' WHERE id = ?").run(coverage.id); store.db.prepare('UPDATE resume_content_selections SET mapped_requirement_ids = ? WHERE id = ?').run(JSON.stringify([coverage.job_requirement_id]), selection.id); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.ok(errors(run).some((item) => item.rule_code === 'uncovered-requirement-claim')); }));
test('duplicate visible claims generate warning', () => withStore((store) => { const setup = prepared(store); content(store, setup.artifactRun, (value) => { const duplicate = { ...value.sections[1].statements[0], statement_id: 'duplicate-statement' }; value.sections[1].statements.push(duplicate); }); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.equal(run.validation_status, 'passed_with_warnings'); assert.ok(run.validation_findings.some((item) => item.rule_code === 'duplicate-visible-claim')); }));
test('section/order mismatch generates warning, not failure', () => withStore((store) => { const setup = prepared(store); content(store, setup.artifactRun, (value) => { const skills = value.sections.splice(1, 1)[0]; value.sections.push(skills); }); const run = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.equal(run.validation_status, 'passed_with_warnings'); assert.ok(run.validation_findings.some((item) => item.rule_code === 'section-order')); }));
test('re-running validation creates an independent immutable run', () => withStore((store) => { const setup = prepared(store); const one = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); const two = store.createResumeValidationRun({ resumeArtifactRunId: setup.artifactRun.id }); assert.notEqual(one.id, two.id); assert.deepEqual(one.artifact_snapshot, two.artifact_snapshot); assert.equal(store.getResumeValidationRun(one.id).id, one.id); }));
