const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { Store } = require('../src/store'); const { MockResumeAstProvider, validateAst, retrieve } = require('../src/resume-ast');
async function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'resume-ast-')); const store = new Store(path.join(dir, 'test.db')); try { await run(store); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
const text = `Jane Doe\nSkills\nPython, SQL, Power BI, workflow automation\nProjects\nAnalytics Dashboard\n• Built dashboards and data storytelling with Power BI.\nExperience\nAcme\n• Automated SQL reporting workflows using Python.`;
const provenance = (ids, exact, extraction_state = 'explicit') => ({ source_span_ids: ids, exact_source_text: exact, extraction_state, source_line_start: Number(ids[0].slice(5)), source_line_end: Number(ids.at(-1).slice(5)), rationale: 'fixture' });
test('async mock provider persists a validated immutable Resume AST Run without Candidate Knowledge writes', () => withStore(async (store) => { const profile = store.createProfile({ name: 'Jane Doe', skills: [] }); const artifact = store.createSourceResumeArtifactVersion({ profileId: profile.id, sourcePath: 'synthetic.txt', parsedText: text }); const run = await store.createResumeAstRun({ profileId: profile.id, artifactId: artifact.artifact.id, provider: new MockResumeAstProvider() }); assert.equal(run.validation_status, 'passed'); assert.ok(run.normalized_ast.projects[0].bullets.length); assert.equal(store.getCandidateKnowledge(profile.id).facts.length, 0); }));
test('invalid nested role, tool, bullet, and provenance fields block the AST', () => { const leaf = (value, ids) => ({ value, provenance: provenance(ids, value) }); const ast = { identity: null, summary_blocks: [], education: [], credentials: [], skills: [], experiences: [{ organization: leaf('Acme', ['line-8']), role: { value: 3, provenance: provenance(['line-8'], '3') }, bullets: 'not-an-array' }], projects: [{ title: leaf('Analytics Dashboard', ['line-5']), technologies: [{ value: 'Power BI', provenance: { source_span_ids: 'line-3' } }], bullets: [leaf('Invented bullet', ['line-6'])] }], additional_sections: [] }; const result = validateAst({ ast, text }); assert.equal(result.validation_status, 'blocked'); assert.ok(result.findings.length >= 3); });
test('real failure shape groups a technology subtitle and wrapped bullet structurally while retaining exact text', async () => withStore(async (store) => { const source = `Jane Doe\nProjects\nCustomer Insights Dashboard\nPower BI / Python / SQL\n• Built executive dashboard storytelling and automated\n  weekly workflow reporting for leadership.`; const profile = store.createProfile({ name: 'Jane Doe', skills: [] }); const artifact = store.createSourceResumeArtifactVersion({ profileId: profile.id, sourcePath: 'real-style.txt', parsedText: source }); const run = await store.createResumeAstRun({ profileId: profile.id, artifactId: artifact.artifact.id, provider: new MockResumeAstProvider() }); assert.equal(run.validation_status, 'passed'); const project = run.normalized_ast.projects[0]; assert.equal(project.title.value, 'Customer Insights Dashboard'); assert.deepEqual(project.technologies.map((item) => item.value), ['Power BI', 'Python', 'SQL']); assert.ok(project.technologies.every((item) => item.provenance.extraction_state === 'structurally_grouped')); assert.equal(project.bullets[0].value, 'Built executive dashboard storytelling and automated weekly workflow reporting for leadership.'); assert.equal(project.bullets[0].provenance.extraction_state, 'structurally_grouped'); }));
test('requirement-driven AST retriever ranks validated blocks with complete provenance', async () => withStore(async (store) => { const profile = store.createProfile({ name: 'Jane Doe', skills: [] }); const artifact = store.createSourceResumeArtifactVersion({ profileId: profile.id, sourcePath: 'synthetic.txt', parsedText: text }); const run = await store.createResumeAstRun({ profileId: profile.id, artifactId: artifact.artifact.id, provider: new MockResumeAstProvider() }); for (const requirement of ['Power BI', 'Python', 'SQL', 'dashboard', 'workflow automation', 'storytelling']) { const matches = retrieve({ normalized_name: requirement }, run.normalized_ast); assert.ok(matches.length, `expected evidence for ${requirement}`); assert.equal(matches[0].rank, 1); assert.equal(typeof matches[0].score, 'number'); assert.equal(typeof matches[0].exact, 'boolean'); assert.ok(matches[0].block.kind); assert.ok(matches[0].block.section); assert.ok(matches[0].rationale); } }));
