const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { Store } = require('../src/store');
function withStore(run) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'resume-tailoring-')); const store = new Store(path.join(dir, 'test.db')); try { run(store); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } }
function prepared(store, description, role = 'Data Analyst') { const profile = store.createProfile({ name: 'Synthetic Candidate' }); const job = store.createJobRequirementProfile({ company: 'Acme', roleTitle: role, jobDescription: description }); const needs = store.createInformationNeedRun({ candidateProfileId: profile.id, jobRequirementProfileId: job.id }); const discovery = store.createEvidenceDiscoveryRun({ informationNeedRunId: needs.id }); const plan = store.createAcquisitionPlanRun({ informationNeedRunId: needs.id, evidenceDiscoveryRunId: discovery.id }); const actions = plan.acquisition_plans.flatMap((item) => item.acquisition_actions); const result = store.createAcquisitionResultRun({ acquisitionPlanRunId: plan.id, captures: actions.map((action) => ({ actionId: action.id, rawCapturedEvidence: { text: 'Synthetic confirmation.' } })) }); return { profile, job, result, source: result.acquisition_results[0] }; }
function facts(store, setup, values) { store.createCandidateKnowledgeIntegrationRun({ candidateProfileId: setup.profile.id, acquisitionResultRunId: setup.result.id, proposals: values.map((value) => ({ entityType: value.entityType || 'skill', value: value.value || { name: value }, confirmationStatus: 'confirmed', confidenceLevel: 'high', sourceEvidenceRefs: [{ type: 'acquisition_result', id: setup.source.id, positiveConfirmation: true }] })) }); }
test('Data Analyst selects SQL, Python, and visualization above unrelated facts', () => withStore((store) => { const setup = prepared(store, 'Required Qualifications:\nSQL required.\nPython required.\nData visualization required.'); facts(store, setup, ['SQL', 'Python', 'Data visualization', 'Communication']); const run = store.createResumeTailoringPlanRun({ candidateProfileId: setup.profile.id, jobRequirementProfileId: setup.job.id }); assert.deepEqual(run.resume_content_selections.slice(0, 3).map((item) => item.selection_state), ['include', 'include', 'include']); assert.equal(run.resume_content_selections.at(-1).selection_state, 'omit'); }));
test('QA testing facts outrank generic communication and uncovered requirements remain unknown', () => withStore((store) => { const setup = prepared(store, 'Required Qualifications:\nRegression testing required.\nTest cases required.\nCommunication skills required.\nSQL required.', 'QA Analyst'); facts(store, setup, ['Regression testing', 'Test cases', 'Communication']); const run = store.createResumeTailoringPlanRun({ candidateProfileId: setup.profile.id, jobRequirementProfileId: setup.job.id }); assert.equal(run.resume_content_selections.find((item) => item.mapped_requirement_ids.length && item.selection_state === 'deprioritize').recommended_section, 'Skills'); assert.equal(run.requirement_coverage.find((item) => item.coverage_status === 'uncovered').supporting_candidate_fact_ids.length, 0); }));
test('claims are bounded, duplicate facts have one selection, source wording is flagged but unchanged, and reruns are immutable', () => withStore((store) => { const setup = prepared(store, 'Required Qualifications:\nSQL required.'); facts(store, setup, ['SQL']); const input = { candidateProfileId: setup.profile.id, jobRequirementProfileId: setup.job.id, sourceResumeArtifact: { id: 'resume-v1', version: '1', content: 'Advanced SQL expert with 8 years experience' } }; const one = store.createResumeTailoringPlanRun(input); const two = store.createResumeTailoringPlanRun(input); const selection = one.resume_content_selections.find((item) => item.selection_state === 'include'); assert.deepEqual(selection.permitted_claim_scope, ['skill_name']); assert.ok(selection.blocked_claim_scopes.includes('years_of_experience')); assert.equal(one.resume_content_selections.length, 1); assert.equal(one.source_resume_analysis_flags.length, 1); assert.notEqual(one.id, two.id); assert.equal(store.getResumeTailoringPlanRun(one.id).id, one.id); }));
