const { createHash } = require('node:crypto');

const SCHEMA_VERSION = 'resume-ast/1.1.0';
const PROMPT_VERSION = 'resume-ast-extraction/1.1.0';
const VALIDATION_POLICY_VERSION = 'resume-ast-validation/1.1.0';
const RETRIEVER_VERSION = 'resume-ast-requirement-retriever/1.1.0';
const EXTRACTION_STATES = new Set(['explicit', 'structurally_grouped', 'possible']);
const RESUME_AST_JSON_SCHEMA = { type: 'object', additionalProperties: false, required: ['identity', 'summary_blocks', 'education', 'credentials', 'skills', 'experiences', 'projects', 'additional_sections'], properties: { identity: { type: ['object', 'null'] }, summary_blocks: { type: 'array' }, education: { type: 'array' }, credentials: { type: 'array' }, skills: { type: 'array' }, experiences: { type: 'array' }, projects: { type: 'array' }, additional_sections: { type: 'array' } } };

function normalize(value) { return String(value || '').replace(/\s+/g, ' ').trim().toLowerCase(); }
function hash(value) { return createHash('sha256').update(String(value)).digest('hex'); }
function linesFor(text) { return String(text).replace(/\r/g, '').split('\n').map((raw_text, index) => ({ id: `line-${index + 1}`, raw_text, line_start: index + 1, line_end: index + 1 })).filter((line) => line.raw_text.trim()); }
function stripBullet(value) { return String(value).trim().replace(/^[\u2022•\-*]+\s*/, ''); }
function provenance(text, lines, extraction_state = 'explicit', rationale = 'Mock extraction copied exact source text.') { return { source_span_ids: lines.map((line) => line.id), exact_source_text: text, source_line_start: lines[0].line_start, source_line_end: lines.at(-1).line_end, extraction_state, confidence: extraction_state === 'explicit' ? 'high' : 'medium', rationale }; }
function leaf(text, lines, state, rationale) { return { value: text, provenance: provenance(text, Array.isArray(lines) ? lines : [lines], state, rationale) }; }

function mockAst(text) {
  const lines = linesFor(text); const ast = { identity: null, summary_blocks: [], education: [], credentials: [], skills: [], experiences: [], projects: [], additional_sections: [] };
  let section = ''; let current = null; let wrappedBullet = null;
  for (const line of lines) {
    const raw = line.raw_text.trim(); const heading = normalize(raw.replace(/:$/, ''));
    if (['experience', 'work experience'].includes(heading)) { section = 'experiences'; current = null; wrappedBullet = null; continue; }
    if (['projects', 'project'].includes(heading)) { section = 'projects'; current = null; wrappedBullet = null; continue; }
    if (['skills', 'technical skills'].includes(heading)) { section = 'skills'; current = null; wrappedBullet = null; continue; }
    if (['education', 'credentials', 'certifications'].includes(heading)) { section = heading; current = null; wrappedBullet = null; continue; }
    if (!ast.identity && /^[A-Z][A-Za-z' -]{2,}$/.test(raw) && !raw.includes(',')) { ast.identity = leaf(raw, line); continue; }
    if (section === 'skills') { raw.split(/[,;|]/).map((value) => value.trim()).filter(Boolean).forEach((value) => ast.skills.push(leaf(value, line))); continue; }
    if (section === 'experiences' || section === 'projects') {
      if (/^[\u2022•\-*]+\s+/.test(raw)) { const textValue = stripBullet(raw); const state = current ? 'structurally_grouped' : 'possible'; const bullet = leaf(textValue, line, state, 'Bullet placement is inferred from resume layout and order.'); if (current) current.bullets.push(bullet); wrappedBullet = bullet; continue; }
      if (wrappedBullet && current) { const textValue = `${wrappedBullet.value} ${raw}`; wrappedBullet.value = textValue; wrappedBullet.provenance = provenance(textValue, lines.slice(lines.indexOf(line) - 1, lines.indexOf(line) + 1), 'structurally_grouped', 'Wrapped bullet placement is inferred from adjacent layout and order.'); continue; }
      if (section === 'projects' && current && current.bullets.length === 0) { raw.split(/[,;|/]/).map((value) => value.trim()).filter(Boolean).forEach((value) => current.technologies.push(leaf(value, line, 'structurally_grouped', 'Technology subtitle is grouped under the preceding project by layout and order.'))); continue; }
      current = section === 'projects' ? { title: leaf(raw, line), technologies: [], start_date: null, end_date: null, bullets: [] } : { organization: leaf(raw, line), role: null, location: null, start_date: null, end_date: null, bullets: [] };
      ast[section].push(current); wrappedBullet = null; continue;
    }
    if (section === 'education') ast.education.push({ institution: leaf(raw, line) });
    else if (section === 'credentials' || section === 'certifications') ast.credentials.push(leaf(raw, line));
  }
  return ast;
}

class MockResumeAstProvider { constructor({ response } = {}) { this.response = response; this.name = 'mock'; this.model = 'deterministic-fixture'; } async extractResumeAst({ text }) { const ast = this.response || mockAst(text); return { provider: this.name, model: this.model, version: SCHEMA_VERSION, rawResponse: JSON.stringify(ast), ast }; } }
class OpenAiCompatibleResumeAstProvider { constructor({ apiKey = process.env.CEP_LLM_API_KEY, baseUrl = process.env.CEP_LLM_BASE_URL, model = process.env.CEP_LLM_MODEL } = {}) { if (!apiKey || !model) throw new Error('OpenAI-compatible provider unavailable: set CEP_LLM_API_KEY and CEP_LLM_MODEL.'); this.apiKey = apiKey; this.baseUrl = baseUrl || 'https://api.openai.com/v1'; this.model = model; this.name = 'openai-compatible'; }
  async extractResumeAst({ text, schema, promptVersion }) { const response = await fetch(`${this.baseUrl.replace(/\/$/, '')}/chat/completions`, { method: 'POST', headers: { Authorization: `Bearer ${this.apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: this.model, response_format: { type: 'json_schema', json_schema: { name: 'resume_ast', strict: true, schema } }, messages: [{ role: 'system', content: `Extract a canonical resume AST only. Every leaf must include exact source spans, exact source text, and extraction_state explicit, structurally_grouped, or possible. Use structurally_grouped only when text is exact but parent placement is inferred from layout/order. Prompt ${promptVersion}.` }, { role: 'user', content: text }] }) }); if (!response.ok) throw new Error(`Resume AST provider failed: ${response.status}`); const json = await response.json(); const rawResponse = json.choices?.[0]?.message?.content; if (!rawResponse) throw new Error('Resume AST provider returned no structured content.'); try { return { provider: this.name, model: this.model, version: SCHEMA_VERSION, rawResponse, ast: JSON.parse(rawResponse) }; } catch { return { provider: this.name, model: this.model, version: SCHEMA_VERSION, rawResponse, ast: null, parseError: 'Provider returned invalid JSON.' }; } }
}
function providerFromConfig(config = {}) { const provider = config.provider || process.env.CEP_LLM_PROVIDER || 'mock'; if (provider === 'mock') return new MockResumeAstProvider(config); if (provider === 'openai-compatible') return new OpenAiCompatibleResumeAstProvider(config); throw new Error(`Resume AST provider unavailable: ${provider}. Use mock or openai-compatible.`); }

function validateAst({ ast, text, parseError }) {
  const findings = []; const sourceLines = linesFor(text); const spanById = new Map(sourceLines.map((line) => [line.id, line]));
  const error = (path, message) => findings.push({ severity: 'error', path, message });
  function array(value, path) { if (!Array.isArray(value)) { error(path, 'Field must be an array.'); return []; } return value; }
  function check(value, path) { if (!value || typeof value !== 'object' || typeof value.value !== 'string' || !value.value.trim() || !value.provenance || typeof value.provenance !== 'object') { error(path, 'Leaf does not satisfy the canonical schema.'); return null; } const p = value.provenance; if (!Array.isArray(p.source_span_ids) || !p.source_span_ids.length || !p.source_span_ids.every((id) => typeof id === 'string') || typeof p.exact_source_text !== 'string' || !EXTRACTION_STATES.has(p.extraction_state) || !Number.isInteger(p.source_line_start) || !Number.isInteger(p.source_line_end) || typeof p.rationale !== 'string') { error(path, 'Leaf provenance is incomplete or invalid.'); return null; } const spans = p.source_span_ids.map((id) => spanById.get(id)); if (spans.some((span) => !span)) { error(path, 'Leaf provenance references a missing source span.'); return null; } const reconstructed = spans.map((span) => stripBullet(span.raw_text)).join(' '); if (!normalize(reconstructed).includes(normalize(value.value)) || normalize(p.exact_source_text) !== normalize(value.value) || p.source_line_start !== spans[0].line_start || p.source_line_end !== spans.at(-1).line_end) { error(path, 'Value is not traceable to exact reconstructable source text.'); return null; } return value; }
  const output = { identity: null, summary_blocks: [], education: [], credentials: [], skills: [], experiences: [], projects: [], additional_sections: [] };
  if (parseError) error('root', parseError); if (!ast || typeof ast !== 'object' || Array.isArray(ast)) { error('root', 'AST must be an object.'); return { normalizedAst: output, findings, validation_status: 'blocked' }; }
  output.identity = ast.identity == null ? null : check(ast.identity, 'identity');
  for (const key of ['summary_blocks', 'credentials', 'skills', 'additional_sections']) for (const [i, value] of array(ast[key], key).entries()) { const checked = check(value, `${key}[${i}]`); if (checked) output[key].push(checked); }
  for (const [i, item] of array(ast.education, 'education').entries()) { if (!item || typeof item !== 'object' || Array.isArray(item)) { error(`education[${i}]`, 'Education entry must be an object.'); continue; } const institution = check(item.institution, `education[${i}].institution`); if (institution) output.education.push({ institution }); }
  for (const [i, item] of array(ast.experiences, 'experiences').entries()) { if (!item || typeof item !== 'object' || Array.isArray(item)) { error(`experiences[${i}]`, 'Experience entry must be an object.'); continue; } const organization = check(item.organization, `experiences[${i}].organization`); const role = item.role == null ? null : check(item.role, `experiences[${i}].role`); const location = item.location == null ? null : check(item.location, `experiences[${i}].location`); const start_date = item.start_date == null ? null : check(item.start_date, `experiences[${i}].start_date`); const end_date = item.end_date == null ? null : check(item.end_date, `experiences[${i}].end_date`); const bullets = array(item.bullets, `experiences[${i}].bullets`).map((value, j) => check(value, `experiences[${i}].bullets[${j}]`)).filter(Boolean); if (organization) output.experiences.push({ organization, role, location, start_date, end_date, bullets }); }
  for (const [i, item] of array(ast.projects, 'projects').entries()) { if (!item || typeof item !== 'object' || Array.isArray(item)) { error(`projects[${i}]`, 'Project entry must be an object.'); continue; } const title = check(item.title, `projects[${i}].title`); const technologies = array(item.technologies, `projects[${i}].technologies`).map((value, j) => check(value, `projects[${i}].technologies[${j}]`)).filter(Boolean); const start_date = item.start_date == null ? null : check(item.start_date, `projects[${i}].start_date`); const end_date = item.end_date == null ? null : check(item.end_date, `projects[${i}].end_date`); const bullets = array(item.bullets, `projects[${i}].bullets`).map((value, j) => check(value, `projects[${i}].bullets[${j}]`)).filter(Boolean); if (title) output.projects.push({ title, technologies, start_date, end_date, bullets }); }
  return { normalizedAst: output, findings, validation_status: findings.some((item) => item.severity === 'error') ? 'blocked' : 'passed' };
}
function blocks(ast) { const items = []; const add = (leafValue, kind, section) => { if (leafValue) items.push({ text: leafValue.value, leaf: leafValue, kind, section }); }; for (const skill of ast.skills || []) add(skill, 'skill', 'skills'); for (const project of ast.projects || []) { add(project.title, 'project', 'projects'); for (const technology of project.technologies || []) add(technology, 'tool', 'projects'); for (const bullet of project.bullets || []) add(bullet, 'bullet', 'projects'); } for (const experience of ast.experiences || []) { add(experience.organization, 'organization', 'experiences'); add(experience.role, 'role', 'experiences'); for (const bullet of experience.bullets || []) add(bullet, 'bullet', 'experiences'); } return items; }
function retrieve(requirement, ast) { const target = normalize(requirement.normalized_name || requirement.name); const terms = target.split(/\s+/).filter((term) => term.length > 1); return blocks(ast).map((block) => { const text = normalize(block.text); const exact = text === target || text.includes(target); const matched = terms.filter((term) => text.includes(term)); const score = (exact ? 100 : 0) + matched.length * 10 + (block.kind === 'skill' || block.kind === 'tool' ? 4 : 0); return { block, exact, score, matched_terms: matched, rationale: exact ? 'Exact requirement text occurs in this validated AST block.' : `Validated AST block overlaps requirement terms: ${matched.join(', ')}.` }; }).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || Number(b.exact) - Number(a.exact) || a.block.text.localeCompare(b.block.text)).map((item, index) => ({ ...item, rank: index + 1 })); }
module.exports = { SCHEMA_VERSION, PROMPT_VERSION, VALIDATION_POLICY_VERSION, RETRIEVER_VERSION, RESUME_AST_JSON_SCHEMA, hash, MockResumeAstProvider, OpenAiCompatibleResumeAstProvider, providerFromConfig, validateAst, retrieve };
